/*
 * By Mas Elkhanza
 */

package gemini;

import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author perpustakaan
 */
public final class ChatGemini extends javax.swing.JDialog {
    private final GeminiService geminiService = new GeminiService();

    /** Creates new form DlgRujuk
     * @param parent
     * @param modal */
    public ChatGemini(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        TabRawat = new javax.swing.JTabbedPane();
        internalFrame7 = new widget.InternalFrame();
        scrollInput5 = new widget.ScrollPane();
        FormInput6 = new widget.PanelBiasa();
        jLabel255 = new widget.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputField = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        BtnClear = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Tanya ki SiTandi ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(750, 720));
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        TabRawat.setBackground(new java.awt.Color(254, 255, 254));
        TabRawat.setForeground(new java.awt.Color(50, 50, 50));
        TabRawat.setName("TabRawat"); // NOI18N
        TabRawat.setPreferredSize(new java.awt.Dimension(457, 480));

        internalFrame7.setBorder(null);
        internalFrame7.setName("internalFrame7"); // NOI18N
        internalFrame7.setPreferredSize(new java.awt.Dimension(102, 480));
        internalFrame7.setLayout(new java.awt.BorderLayout(1, 1));

        scrollInput5.getVerticalScrollBar().setUnitIncrement(50);
        scrollInput5.setName("scrollInput5"); // NOI18N
        scrollInput5.setPreferredSize(new java.awt.Dimension(102, 557));

        FormInput6.setBackground(new java.awt.Color(240, 242, 245));
        FormInput6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        FormInput6.setName("FormInput6"); // NOI18N
        FormInput6.setPreferredSize(new java.awt.Dimension(700, 520));
        FormInput6.setLayout(null);

        jLabel255.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel255.setText("💬 Chat dengan SiTandi");
        jLabel255.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel255.setForeground(new java.awt.Color(41, 128, 185));
        jLabel255.setName("jLabel255"); // NOI18N
        FormInput6.add(jLabel255);
        jLabel255.setBounds(10, 5, 250, 25);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199), 1));
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        messageField.setEditable(false);
        messageField.setColumns(20);
        messageField.setRows(5);
        messageField.setLineWrap(true);
        messageField.setWrapStyleWord(true);
        messageField.setFont(new java.awt.Font("Segoe UI", 0, 13));
        messageField.setBackground(new java.awt.Color(255, 255, 255));
        messageField.setForeground(new java.awt.Color(44, 62, 80));
        messageField.setMargin(new java.awt.Insets(10, 10, 10, 10));
        messageField.setName("messageField"); // NOI18N
        jScrollPane1.setViewportView(messageField);

        FormInput6.add(jScrollPane1);
        jScrollPane1.setBounds(10, 35, 670, 335);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199), 1));
        jScrollPane2.setName("jScrollPane2"); // NOI18N

        inputField.setColumns(20);
        inputField.setRows(3);
        inputField.setFont(new java.awt.Font("Segoe UI", 0, 13));
        inputField.setBackground(new java.awt.Color(255, 255, 255));
        inputField.setForeground(new java.awt.Color(44, 62, 80));
        inputField.setMargin(new java.awt.Insets(8, 10, 8, 10));
        inputField.setName("inputField"); // NOI18N
        inputField.setLineWrap(true);
        inputField.setWrapStyleWord(true);
        jScrollPane2.setViewportView(inputField);

        FormInput6.add(jScrollPane2);
        jScrollPane2.setBounds(10, 375, 670, 75);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("📤 Kirim");
        jButton1.setBackground(new java.awt.Color(52, 152, 219));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setFocusPainted(false);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        FormInput6.add(jButton1);
        jButton1.setBounds(10, 460, 150, 40);

        BtnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnClear.setMnemonic('C');
        BtnClear.setText("Bersihkan");
        BtnClear.setToolTipText("Alt+C");
        BtnClear.setName("BtnClear"); // NOI18N
        BtnClear.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        FormInput6.add(BtnClear);
        BtnClear.setBounds(280, 460, 140, 40);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        FormInput6.add(BtnKeluar);
        BtnKeluar.setBounds(540, 460, 140, 40);

        scrollInput5.setViewportView(FormInput6);

        internalFrame7.add(scrollInput5, java.awt.BorderLayout.CENTER);

        TabRawat.addTab("SiTandi", internalFrame7);

        internalFrame1.add(TabRawat, java.awt.BorderLayout.CENTER);
        TabRawat.getAccessibleContext().setAccessibleName("SiTandi");

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        kirimPesan();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        messageField.setText("");
        inputField.setText("");
        inputField.requestFocus();
    }//GEN-LAST:event_BtnClearActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            ChatGemini dialog = new ChatGemini(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnClear;
    private widget.Button BtnKeluar;
    private widget.PanelBiasa FormInput6;
    private javax.swing.JTabbedPane TabRawat;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame7;
    private javax.swing.JButton jButton1;
    private widget.Label jLabel255;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messageField;
    private javax.swing.JTextArea inputField;
    private widget.ScrollPane scrollInput5;
    // End of variables declaration//GEN-END:variables

    /**
     * Method untuk mengirim pesan ke SiTandi dan menampilkan respons
     */
    private void kirimPesan() {
        // Ambil pesan dari input field
        String pesan = inputField.getText();

        // Validasi input - jika input kosong
        if (pesan == null || pesan.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Silakan ketik pesan terlebih dahulu",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            inputField.requestFocus();
            return;
        }

        final String pesanFinal = pesan.trim();

        // Tampilkan pesan user di area percakapan
        messageField.append(">>> Anda: " + pesanFinal + "\n");

        // Kosongkan input field
        inputField.setText("");

        // Disable tombol dan tampilkan loading cursor
        jButton1.setEnabled(false);
        inputField.setEnabled(false);
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        // Kirim ke SiTandi menggunakan thread terpisah agar UI tidak freeze
        new Thread(() -> {
            try {
                String response = geminiService.generateResponse(pesanFinal);

                // Update UI di Event Dispatch Thread
                java.awt.EventQueue.invokeLater(() -> {
                    messageField.append(">>> SiTandi: " + response + "\n\n");
                    messageField.setCaretPosition(messageField.getDocument().getLength());
                    jButton1.setEnabled(true);
                    inputField.setEnabled(true);
                    inputField.requestFocus();
                    ChatGemini.this.setCursor(Cursor.getDefaultCursor());
                });

            } catch (Exception e) {
                // Update UI dengan error message
                java.awt.EventQueue.invokeLater(() -> {
                    messageField.append("!!! Error: " + e.getMessage() + "\n\n");
                    jButton1.setEnabled(true);
                    inputField.setEnabled(true);
                    inputField.requestFocus();
                    ChatGemini.this.setCursor(Cursor.getDefaultCursor());

                    JOptionPane.showMessageDialog(ChatGemini.this,
                        "Terjadi kesalahan: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                });
                System.out.println("Error saat mengirim pesan: " + e.getMessage());
            }
        }).start();
    }

    /**
     * Method untuk menampilkan form
     */
    public void setTampil(){
       TabRawat.setSelectedIndex(0);
    }

}
